#!/bin/bash

if [ $# = 1 ]; then
    ragel -pV $1 | dot -Tsvg > ${1%.*}.svg && start ${1%.*}.svg
elif [ $# = 2 ]; then
    ragel -pVM $2 $1 | dot -Tsvg > $2.svg && start $2.svg
elif [ $# = 3 ]; then
    ragel -pVM $2 -S $3 $1 | dot -Tsvg > $3_$2.svg && start $3_$2.svg
else
    echo 'you dumbass'
fi
